name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release"
        required: true
        default: "1.0.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt install build-essential
          sudo apt install libhidapi-dev
          sudo apt install libnvidia-ml-dev
      - name: build
        run: |
          gcc -fdiagnostics-color=always -g ./panel.c -o ./panel -lhidapi-libusb -lhidapi-hidraw

      - name: Create deb package
        run: |
          VERSION="${{ inputs.tag }}"
          PKG_NAME="harboros-subscreen_${VERSION}_linux_amd64"
          PKG_DIR="./deb-package/${PKG_NAME}"

          mkdir -p ${PKG_DIR}/DEBIAN
          mkdir -p ${PKG_DIR}/usr/bin
          mkdir -p ${PKG_DIR}/etc/systemd/system

          cp ./panel ${PKG_DIR}/usr/bin/panel
          chmod +x ${PKG_DIR}/usr/bin/panel

          cp ./debian/harboros-subscreen.service ${PKG_DIR}/etc/systemd/system/

          cp ./debian/control ${PKG_DIR}/DEBIAN/control
          sed -i "s/VERSION_PLACEHOLDER/${VERSION}/g" ${PKG_DIR}/DEBIAN/control

          cp ./debian/postinst ${PKG_DIR}/DEBIAN/postinst
          chmod +x ${PKG_DIR}/DEBIAN/postinst

          cp ./debian/prerm ${PKG_DIR}/DEBIAN/prerm
          chmod +x ${PKG_DIR}/DEBIAN/prerm

          dpkg-deb --build ${PKG_DIR}
          mv ./deb-package/${PKG_NAME}.deb ./artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ inputs.tag }}
          name: v${{ inputs.tag }}
          generate_release_notes: true
          files: |
            ./artifacts/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
